[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./lib/damn-vulnerable-defi/builds/uniswap/" },
    { access = "read", path = "./lib/damn-vulnerable-defi/test/the-rewarder/dvt-distribution.json" },
    { access = "read", path = "./lib/damn-vulnerable-defi/test/the-rewarder/weth-distribution.json" },
    { access = "read", path = "./lib/damn-vulnerable-defi/test/withdrawal/withdrawals.json" },
]
bytecode_hash = "none"
